version: 2
project_name: sketch

# Build configuration
before:
  hooks:
    - make clean

builds:
  - id: sketch
    # Note: this build corresponds to build/outie.sh; please keep them in sync.
    main: ./cmd/sketch
    binary: sketch
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - outie
    ldflags:
      - -X main.release={{.Version}}
      - -X main.builtBy=goreleaser
    env:
      - SKETCH_VERSION={{.Version}}
      - BUILT_BY=goreleaser
    hooks:
      pre:
        - ./build/webui.sh
        - ./build/innie.sh

archives:
  - id: releaseArchive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
  - id: releaseBinary
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

signs:
  - id: ed25519-sign
    cmd: selfupdatectl
    args:
      - "sign"
      - "--private-key=/dev/stdin"
      - "${artifact}"
    stdin: "{{ .Env.SELFUPDATE_SIGNING_KEY }}"
    signature: "${artifact}.ed25519"
    artifacts: all

release:
  github:
    owner: boldsoftware
    name: sketch
  draft: false
  prerelease: false
