version: 2
project_name: sketch

# Build configuration
before:
  hooks:
    - make clean

builds:
  - id: sketch
    # Note: this build corresponds to 'make outie'; please keep them in sync.
    main: ./cmd/sketch
    binary: sketch
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - outie
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.makefile=goreleaser
    hooks:
      pre:
        - ./.goreleaser/build-target.sh

archives:
  - id: releaseArchive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: boldsoftware
    name: sketch
  draft: false
  prerelease: false
