version: 2
project_name: sketch

# Build configuration
before:
  hooks:
    - "npm ci --prefix webui"
    - "npm run build --prefix webui"

builds:
  - id: sketch
    main: ./cmd/sketch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: releaseArchive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: boldsoftware
    name: sketch
  draft: false
  prerelease: false
